### ISSUE TITLE
Error: Cannot find module 'zlibjs/bin/gzip.min.js'

### ISSUE THREAD

**Issue by TheStruggleForAntiSpaghetti** [digital-sound-antiques/vgm-conv#1]
With it's ability for frequency conversion, I'm very keen on trying it, but I seem to be unable to get it to run. The error in the subject appears every time.

Any help would be appreciated.
 
I'm using Windows Home x64 v1909 build 18363.720.

**Comment by okaxaki** [comment]
Thanks for the bug report. I have fixed the problem and published vgm-conv 0.5.6.
Please try `npm install -g vgm-conv` again.

**Comment by TheStruggleForAntiSpaghetti** [comment]
Confirming being fixed. Thanks :)
