### ISSUE TITLE
ym2608 converted to OPL series rhythm channel lost

### ISSUE THREAD

**Issue by denjhang** [digital-sound-antiques/vgm-conv#10]
Can the rhythm channel be retained during conversion? At present, the rhythm channel of OPLL can be converted to ym2608

**Comment by okaxaki** [comment]
YM2608 to YM2413 rhythm conversion has been supported at [0.8.2](https://github.com/digital-sound-antiques/vgm-conv/commit/0ccec253805fef30a2bc7fa793c4da3ad2ac707f).
