### ISSUE TITLE
When ym2203 is converted to ymf262, the ssg volume is too loud

### ISSUE THREAD

**Issue by denjhang** [digital-sound-antiques/vgm-conv#14]
Is it possible to add the volume adjustment function of the conversion chip? This will be useful.

**Comment by okaxaki** [comment]
The problematic VGM file is likely to have an extra header to reduce the volume of the SSG part.
The following option has been added at 0.8.22.

```
YM2203 to OPL (YM3812/Y8950/YM3526/YMF262) OPTIONS

  -D ssgAttenuation=n   Set SSG volume attenuation level to 0.75*n(dB). The effective range is -63<=n<=63.
```
