### ISSUE TITLE
Conversion from FM2203 ssg to AY8910 not working.

### ISSUE THREAD

**Issue by TheStruggleForAntiSpaghetti** [digital-sound-antiques/vgm-conv#2]
In the options, it says vgm-conv support FM2203 ssg conversion to AY8910, but while trying to convert:

FM2203 tune "01 Start ~ Theme of Terracresta.vgz", downloaded from here:
[https://vgmrips.net/packs/pack/terra-cresta-arcade]
 
to AY8910 by using
 
`vgm-conv -i "01 Start ~ Theme of Terracresta.vgz" -f fm2203 -t ay8910 -o "01 Start ~ Theme of Terracresta-conv.vgz"`
 
I get this response:
`Converter from fm2203 to ay8910 is not implemented.`.

**Comment by okaxaki** [comment]
`fm2203` is incorrect. Use `ym2203` instead.

**Comment by TheStruggleForAntiSpaghetti** [comment]
I slip back into the shadows in shame... 😊
Sorry.
