### ISSUE TITLE
ym2612 to ym2413: custom instrument mapping

### ISSUE THREAD

**Issue by denjhang** [digital-sound-antiques/vgm-conv#22]
My idea is to allow custom instrument mapping, such as mapping a certain instrument in the YM2612 VGM to a certain instrument in the YM2413. Or support the use of YM2413 user-defined instrument (instrument 0)

**Comment by okaxaki** [comment]
See this: https://github.com/digital-sound-antiques/vgm-conv#voice-table-beta

**Comment by denjhang** [comment]
So where should this code be added or modified? I don't know exactly how to use this code.

**Comment by denjhang** [comment]
![截图未命名0816183844](https://user-images.githubusercontent.com/61811583/129551238-7b71691d-bd17-458f-880d-ba0d7f1df545.jpeg)
![截图未命名0816183740](https://user-images.githubusercontent.com/61811583/129551254-8be77490-e1bc-449c-ac32-1bf684990f05.jpeg)

**Comment by denjhang** [comment]
It seems that the definition of instrument 0 (user-defined instrument) is currently not supported. What I am talking about here is not the 15 instruments that come with the YM2413.

**Comment by denjhang** [comment]
"520030001c1f257fdf1fdf1f0709068607060608251515f5000000000100"
What does this bunch of numbers represent? I guess it should be an OPN instrument. But this seems not very intuitive and difficult to understand. Can this bunch of numbers be converted into more readable FM instrument parameters?

**Comment by okaxaki** [comment]
> So where should this code be added or modified? I don't know exactly how to use this code.

This code fragment is a configuration file. `vgm-conv --voiceTable <file>` option can be used to load that code.

> It seems that the definition of instrument 0 (user-defined instrument) is currently not supported. 

You can define the user-defined instruments with the program number from 16 to 1023 at the `voices` section of the configuration. 

```js
const [HH, CYM, TOM, SD, BD] = [1 << 10, 1 << 11, 1 << 12, 1 << 13, 1 << 14];
const [Violin, Piano, Guitar, Flute, Clarinet, Oboe, Trumpet, Organ, Horn, Synthsizer, Harpsicode, Vibraphone, SynthBass, WoodBass, ElectricBass] = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15];

module.exports = {
  voiceTable: {
     opn2opll: {
...
        voices: {
          // Original Tones can be defined from program number 16 to 1023.
          16: [0x01, 0x01, 0x1c, 0x07, 0xf0, 0xd7, 0x00, 0x11],
        },
...
```

> "520030001c1f257fdf1fdf1f0709068607060608251515f5000000000100" What does this bunch of numbers represent?

This is hash of the instrument. Please run `vgm-conv -f ym2612 -t ym2413 vgmfile` first. Then hashs can be seen on the console after running vgm-conv without specifiying voice table file.

**Comment by denjhang** [comment]
I can indeed see the hash of the instrument, but the CMD disappears after the conversion is completed, and I have no way to record these values. And can the hash of the instrument become a readable OPN instrument value? I don't know the tone of this pile of numbers based on the hash value alone.
In addition, define OPLL tone 16: [0x01, 0x01, 0x1c, 0x07, 0xf0, 0xd7, 0x00, 0x11], how to understand this pile of hexadecimal arrays?

In fact, I hope that these numbers can be converted into MML format instrument definitions, such as MML2VGM format
![截图未命名0816194038](https://user-images.githubusercontent.com/61811583/129558162-6e890ea6-36a8-43ad-a23b-8c38ffa4ec1e.jpeg)
![截图未命名0816194050](https://user-images.githubusercontent.com/61811583/129558169-8d8ece2e-4a1b-4f9b-bb7a-b8deecb6d2fe.jpeg)


Or the instrument definition in MML format can be converted to [0x01, 0x01, 0x1c, 0x07, 0xf0, 0xd7, 0x00, 0x11] this format or "520030001c1f257fdf1fdf1f0709068607060608251515f5000000000100" such confusing numbers.
I don't seem to find any relevant tools at the moment.

**Comment by okaxaki** [comment]
Sorry this app itself still highly experimental and just only provide functionality for programmers. It does not provide user-friendly interface.  I understand what you expect (not limited to this issue) and I hope I can provide interface for common users, but due to my time constraints, I have not been able to work on the user interface.

**Comment by denjhang** [comment]
I added pause to vgm-conv.cmd to solve the problem of CMD disappearing.

**Comment by denjhang** [comment]
vgm-conv -f ym2612 -t ym2413 --voiceTable piano-ins.js in.vgm -o out.vgm
I found an error when I ran this statement. Could you please help me to find out where the problem is.

![截图未命名0816203903](https://user-images.githubusercontent.com/61811583/129565185-981ac3e5-8920-4f98-89aa-452a550def94.jpeg)
![截图未命名0816203923](https://user-images.githubusercontent.com/61811583/129565198-b13ee541-28d6-4477-9f66-7e21e218369e.jpeg)

**Comment by denjhang** [comment]
I currently modify opn-to-ym2413-converter.js to take effect. And OPLL tone color register can be viewed through MDPlayer.
![截图未命名0816205332](https://user-images.githubusercontent.com/61811583/129566876-9a753e03-247c-4b56-93f3-85d22d15fda8.jpeg)
![截图未命名0816205346](https://user-images.githubusercontent.com/61811583/129566885-5bf538b1-3ffe-4474-ad8e-6a01dcf05619.jpeg)

**Comment by okaxaki** [comment]
I think comma is missing. 

![129565198-b13ee541-28d6-4477-9f66-7e21e218369e](https://user-images.githubusercontent.com/8530297/129579396-4eb10609-7139-43eb-97c1-659cdc782ae9.jpg)

VS code is my recommendation to check the JavaScript syntax.
