### ISSUE TITLE
sn76489 to ay8910 noise frequency

### ISSUE THREAD

**Issue by denjhang** [digital-sound-antiques/vgm-conv#29]
When the four channels of sn76489 are used at the same time, there is no distinction of noise frequency after switching to AY8910.
![截图未命名0816225157](https://user-images.githubusercontent.com/61811583/129584152-21fed8d6-5743-4982-b295-22ebd9462737.jpeg)
![截图未命名0816225215](https://user-images.githubusercontent.com/61811583/129584159-1ec3e145-0734-440c-a79f-227f5358667b.jpeg)

**Comment by okaxaki** [comment]
Humm, it is very strange that the rate `2` mapped into the freq `31`.  If you use vgm-conv 0.8.4, could you try 0.8.5 again?

**Comment by denjhang** [comment]
ok

**Comment by okaxaki** [comment]
I noticed that there is the bug where the periodic noise flag is inverted internally. I will fix this in the next version.

**Comment by okaxaki** [comment]
This bug should be fixed on 0.8.7.
