### ISSUE TITLE
Feature request: Add YM2149.

### ISSUE THREAD

**Issue by TheStruggleForAntiSpaghetti** [digital-sound-antiques/vgm-conv#3]
Could you please also support the YM2149? It's very similar to the AY8910. If supported, we can use it to frequency convert those too.
 
TIA.

**Comment by okaxaki** [comment]
Is there any problematic ym2419 VGM file?
In my design, ym2419 vgm can also be converted by using ay8910 option.

**Comment by TheStruggleForAntiSpaghetti** [comment]
Well, I'd like to convert an MSX2 tune which is 60Hz to 50Hz;
[https://vgmrips.net/packs/pack/vampire-killer-msx2) - "02. Vampire Killer](https://vgmrips.net/packs/pack/vampire-killer-msx2) - "02. Vampire Killer"
 
How would I go about that?
 
I've tried:
`vgm-conv -i VampireKiller-Title_MSX2.vgm -f ay8910 -t ay8910 -c 50 -o VampireKiller-Title_MSX2_50Hz.vgm`

But that results in a file that produces no sound.

**Comment by okaxaki** [comment]
60Hz/50Hz is frequency of VSYNC. It is different from chip clock (ex. 3.58MHz, 4MHz). 
vgm-conv only supports chip clock conversion.

**Comment by TheStruggleForAntiSpaghetti** [comment]
I'm still trying to make sense of terminology like Soundchip Frequency, V-Sync (also V-Blank, "Frame") and if/how that relates to the CPU clock.
 
Thanks for taking it up as a feature request 😎
