### ISSUE TITLE
sn76489 to ay8910 cannot convert VGM based on snooze tracker

### ISSUE THREAD

**Issue by denjhang** [digital-sound-antiques/vgm-conv#32]
[puzzledIV.zip](https://github.com/digital-sound-antiques/vgm-conv/files/6993483/puzzledIV.zip)

**Comment by okaxaki** [comment]
vgm-conv 0.8.12 can convert the file you attached.

I confirmed that converted .vgm can be played on vgmplay but I couldn't on the real AY8910. My AY8910 chip is connected through USB serial port so it may have a band-width problem.

Please check the conversion result If you have a reliable player for the real AY8910.
