### ISSUE TITLE
Periodic noise conversion pitch error

### ISSUE THREAD

**Issue by denjhang** [digital-sound-antiques/vgm-conv#35]
The SN76489 periodic noise sounds like a bass bass near A1~A2, but the sound is very high after conversion.
[landfex.zip](https://github.com/digital-sound-antiques/vgm-conv/files/6996491/landfex.zip)
![截图未命名0817094943](https://user-images.githubusercontent.com/61811583/129651162-8c86064b-90e7-4a27-a7b0-6bfd6aeee2b2.jpeg)
![截图未命名0817095052](https://user-images.githubusercontent.com/61811583/129651165-9b8f148d-f4ef-4ab1-8099-eb4042db3eee.jpeg)

**Comment by okaxaki** [comment]
I noticed this and I think it is not a bug. The periodic noise part shares the same frequency register of AY8910 tone channel C, so unexpected result can be obtained with some songs. 

I already tried to use AY8910's envelope to simulate the periodic noise but I had not got good result yet.

Another approach is to multiply the frequency of periodic noise if the channel 2 is not used by other part. I will try such approach in future.

**Comment by okaxaki** [comment]
I just thought about it for a while and then I've implemented the functionality to shift the pitch of the periodic noise which can also be controlled by the following option. 

```
  -D periodicNoisePitchShift=n
    Specify the pitch shift amount of the periodic noise conversion. pow(2, -n) will be multiplied to the frequency. The     
    default value is 2.   
```

However, it does not allow for fine pitch tuning, so don't expect much. Even if this approach is taken, the bass part of landfex.zip still seems to be detuned. I suspect that the audible pitch of the periodic noise may be different from the theoretical pitch, but I can't actually confirm this with the real SN76489 hardware. If a frequency-pitch table for the periodic noise of the SN76489 exists somewhere, please let me know.

Further, side-effects possibly be introduced by this patch. If you find something wrong, please open the new issue.
