### ISSUE TITLE
Possibility to specify multiple parameters

### ISSUE THREAD

**Issue by denjhang** [digital-sound-antiques/vgm-conv#37]
vgm-conv -f sn76489 -t ay8910 -D mixChannel=0 -D periodicNoisePitchShift=5 in.vgm -o out.vgm

I found that only -D periodicNoisePitchShift=5 is effective, and the -D mixChannel=0 written in front is not effective.

**Comment by okaxaki** [comment]
This bug is not related to the multiplexity of options but `mixChannel=0` was simply ignored inside the converter. Fixed at 0.8.9.
