### ISSUE TITLE
Volume adjustment option after periodic noise conversion

### ISSUE THREAD

**Issue by denjhang** [digital-sound-antiques/vgm-conv#38]
[landfex.zip](https://github.com/digital-sound-antiques/vgm-conv/files/6997137/landfex.zip)

I feel that the volume of the periodic noise here is lower, and I hope to provide the option to adjust the volume.

**Comment by okaxaki** [comment]
The following two options have been added:

```
  -D noiseVolume=n            Specify the volume offset to the white noise. The default value is 0.                                                                                                                                          
  -D periodicNoiseVolume=n    Specify the volume offset to the periodic noise. The default value is 0. 
```

However, landfex.zip's periodic noise volume is already high, this might not be much help.
I have no plan to add option to attenuate tone channels. That should be done outside vgm-conv if required.
