### ISSUE TITLE
NTSC/PAL conversion

### ISSUE THREAD

**Issue by okaxaki** [digital-sound-antiques/vgm-conv#4]
from #3

**Comment by TheStruggleForAntiSpaghetti** [comment]
Hi 🙂
May I ask why this is regarded Invalid?

**Comment by okaxaki** [comment]
Sorry, I misunderstood at #3. The VGM format itself is independent from NTSC/PAL. It should play back at the same speed regardless of whether it was recorded in PAL or NTSC.

If the playback speed is different, there is something wrong with either the VGMPlayer or the tool used for recording.
