### ISSUE TITLE
Unable to convert some GameGear VGM

### ISSUE THREAD

**Issue by denjhang** [digital-sound-antiques/vgm-conv#40]
[StreetsOfRageII-GG.zip](https://github.com/digital-sound-antiques/vgm-conv/files/6997966/StreetsOfRageII-GG.zip)

**Comment by okaxaki** [comment]
This is a [vgm-parser](https://github.com/digital-sound-antiques/vgm-parser) issue. Fixed at vgm-conv 0.8.13.
