### ISSUE TITLE
A new method for FM to produce variable frequency noise

### ISSUE THREAD

**Issue by denjhang** [digital-sound-antiques/vgm-conv#44]
Please study this VGM file carefully. It uses YM2612 to generate variable frequency noise with a tone lower than C1, which is similar to PSG. I think this will help improve FM analog PSG. Although the VGM in the file uses OPN2, I actually think that the OPL series can also do this.
[Phobos.zip](https://github.com/digital-sound-antiques/vgm-conv/files/7002747/Phobos.zip)

**Comment by okaxaki** [comment]
Is there any document of this approach? I think I can study but I would like to avoid to invent the wheel and wanna save my time.

**Comment by denjhang** [comment]
There is no related document. No one is currently conducting research on this. This VGM file was also discovered by accident. Before that, I always thought that FM could not emit white noise with variable frequencies.

**Comment by denjhang** [comment]
I guess no more than 5 people are aware of this phenomenon.

**Comment by okaxaki** [comment]
I have investigated the vgm. First I thought it uses SSG-EG but it doen't. The noise is simply generated by using very very low frequency (fnum<90, blk=1 or 2). The voice parameter itself is not surprising, it may be well-known.

```
'@ N 000
   AR  DR  SR  RR  SL  TL  KS  ML  DT  AM  SSGEG
'@ 031 000 000 015 015 000 000 000 000 000 000
'@ 031 000 000 015 015 000 000 001 000 000 000
'@ 031 000 009 015 015 000 000 000 000 000 000
'@ 031 000 000 015 015 000 000 000 000 000 000
   AL  FB
'@ 000 000
```

I think the parameter above can be used for AY noise n=31 case, but I'm not sure if it is possible to create an intermediate gradient for other noise frequencies.

I attach the test vgm for this noise on OPN2. 
[opn_noise_test.vgm.zip](https://github.com/digital-sound-antiques/vgm-conv/files/7008214/opn_noise_test.vgm.zip)

I did the same test with OPLL, but it seems that it can only generate white-like noise.
[opll_noise_test.vgm.zip](https://github.com/digital-sound-antiques/vgm-conv/files/7008238/opll_noise_test.vgm.zip)

**Comment by denjhang** [comment]
As for the noise of the middle gradient, please watch this video. I use multiple tones to superimpose white noise of the same frequency.It can also produce similar periodic noise.

https://www.youtube.com/watch?v=4c0PFs9nNEg
https://www.youtube.com/watch?v=DWXR75rEbNA

**Comment by okaxaki** [comment]
I mean this is a well-known approach. not perfect but applicable for some music.
