### ISSUE TITLE
When using PSG envelope to simulate periodic noise, its volume cannot be increased

### ISSUE THREAD

**Issue by denjhang** [digital-sound-antiques/vgm-conv#45]
vgm-conv -f sn76489 -t ay8910 -D periodicNoiseAssignment=env.saw -D periodicNoiseVolume=5 -D periodicNoisePitchShift=4 in.vgm -o out.vgm

I tested that periodicNoiseVolume=5 and periodicNoiseVolume=0 have the same effect.

**Comment by denjhang** [comment]
vgm-conv -f sn76489 -t ay8910 -D periodicNoiseAssignment=tone -D periodicNoiseVolume=3 -D periodicNoisePitchShift=4 in.vgm -o out.vgm

So it works

**Comment by denjhang** [comment]
I think it should be possible to adjust the volume of the sawtooth wave or triangle wave generated by the envelope. If it cannot be adjusted, then the volume of the other two channels can be lowered. There is currently no other tool to do this.

**Comment by okaxaki** [comment]
This is a hardware limitation. There's no way to control the volume of AY8910's H/W envelope.

**Comment by okaxaki** [comment]
Related: #46
