### ISSUE TITLE
Volume adjustment function

### ISSUE THREAD

**Issue by denjhang** [digital-sound-antiques/vgm-conv#46]
Now that the clock can be adjusted, I hope to be able to adjust the volume of each channel. In this way, you can rebalance each channel of the VGM. I think this is a very useful function.
At present, I hope to realize the volume adjustment of AY8910 or SN76489.

**Comment by okaxaki** [comment]
Here is the new options:

```
  -D channelAttenuationMap=n1,n2,n3,n4   Volume attenuation mapping for SN76489 channels. n1, n2, ... n4 correspond to SN76489's ch1, ch2, ... ch4 respectively. The default value is 0,0,0,0.                              
  -D whiteNoiseAttenuation=n             Additional volume attenuation for the white noise. This value will be added to the n4 specified on volumeAttenuationMap. The default value is 0.                                   
  -D periodicNoiseAttenuation=n          Additional volume attenuation for periodic noise. This value will be added to the n4 specified on volumeAttenuationMap. The default value is 0.   
```

BTW, I think this feature is too complex for vgm-conv. As I mentioned before, filter functions should be external. So these options will be changed or removed in future.
