### ISSUE TITLE
The sn76489 noise is converted to the specified frequency noise of AY8910

### ISSUE THREAD

**Issue by denjhang** [digital-sound-antiques/vgm-conv#52]
During the conversion, I hope to add a frequency mapping option:
SN76489 noise rate0 ->AY8910 noise 31
SN76489 noise rate1 ->AY8910 noise 15
SN76489 noise rate2 ->AY8910 noise 7
I hope the numbers on the right can be customized.

**Comment by okaxaki** [comment]
The following option has been added at 0.8.16.

```
  -D noisePitchMap=n1,n2,n3   The noise frequency of AY8910. n1, n2 and n3 correspond to SN76489's noise frequency 0, 1 and 2 respectively. The default value is 7,15,31.
```
