### ISSUE TITLE
OPL3/OPL2/OPL1 to OPLL

### ISSUE THREAD

**Issue by denjhang** [digital-sound-antiques/vgm-conv#53]
At least I think OPL2 and OPL1 can be converted to OPLL, because the channels are the same, the timbre can be approximated. (Similar to OPN to OPLL)

**Comment by okaxaki** [comment]
Please do not open the issue about a request for conversion patterns.
All chip-to-chip conversions are possible. If we create issues for unimplemented conversions, we can create issues for as many combinations of chips as we want, which is not an apropriate use of GitHub issues.
