### ISSUE TITLE
Cannot read property '176' of undefined

### ISSUE THREAD

**Issue by ReimuNotMoe** [digital-sound-antiques/vgm-conv#57]
Version: `0.9.0`
Command line: `vgm-conv -f ym2203.fm -t ymf262 | vgm-conv -f ym2203.ssg -t ay8910 | vgm-conv -f ay8910 -t ymf262`

Output:
```
ym2203(3993600Hz) => ymf262(14318180Hz)
ym2203(3993600Hz) => ay8910(1789772.5Hz)
Cannot read property '176' of undefined
```

**Comment by okaxaki** [comment]
Hi, thank you for your report. This has been fixed at vgm-conv 0.9.1.
