### ISSUE TITLE
YM2413+AY8910 to ymf262 error

### ISSUE THREAD

**Issue by denjhang** [digital-sound-antiques/vgm-conv#67]
My conversion step is
1. Convert ym2413+ay8910 to ymf262+ay8910
2. ymf262+ay8910 converted to only ymf262

When I use vgm-conv 0.8.0, there is no problem in the whole process, but when I use 0.10.0, the converted ymf262 sounds a lot wrong.

**Comment by okaxaki** [comment]
It seems that we got unexpected result if ay8910 to ymf262 conversion is given while the ymf262 part already exists.
May be similar to #63.

**Comment by denjhang** [comment]
> It seems that we get an unexpected result if ay8910 to ymf262 conversion is given while the ymf262 part already exists. May be similar to #63.

Under Windows 10 system, I cannot use the following statement:
`vgm-conv -f ay8910 -t ymf262 -i 01\ Opening.vgz | vgm-conv -f ym2413 -t ymf262 -o test.vgm`

It seems that Windows 10 does not allow multiple statements at the same time.

**Comment by okaxaki** [comment]
Please see [this comment](https://github.com/digital-sound-antiques/vgm-conv/issues/63#issuecomment-1383990378).
