### ISSUE TITLE
YM2413 conversion to YM3812 or YMF262 - Hi-hat in rhythm mode plays too loudly

### ISSUE THREAD

**Issue by ccacook98** [digital-sound-antiques/vgm-conv#75]
I noticed when listening to the Phantasy Star YM2413 OST converted to OPL2 or OPL3 using vgm-conv that the rhythm mode hi-hat is louder than it should be. I've attached wave files of what is expected (the original YM2413 version) and what the converter produces. You'll find them inside the attached zip file.

I think this may be a bug in vgm-conv because this doesn't happen when playing the same source VGM in OPLx's SBVGM, which performs a similar register remapping to play OPLL VGMs on a Sound Blaster card's OPL2.

Thanks for developing this awesome tool!
[PSIntro-vgmconv.zip](https://github.com/digital-sound-antiques/vgm-conv/files/11763966/PSIntro-vgmconv.zip)

**Comment by okaxaki** [comment]
Sorry for the late response.
The relative volume of all rhythm notes, not just Hi-Hat, was incorrect.
Fixed in version 0.11.1.
