### ISSUE TITLE
BUG occurs when converting YM2612 to YM2151.

### ISSUE THREAD

**Issue by denjhang** [digital-sound-antiques/vgm-conv#78]
[Phobos-org.zip](https://github.com/digital-sound-antiques/vgm-conv/files/14284407/Phobos-org.zip)
When I convert Phobos-org.vgm to YM2151, the converted sound is incorrect.

**Comment by okaxaki** [comment]
I think this VGM uses SSG-EG, that is difficult to support.

**Comment by denjhang** [comment]
[Castlevania - Bloodlines (Castlevania - The New Generation, Vampire Killer).zip](https://github.com/digital-sound-antiques/vgm-conv/files/14297333/Castlevania.-.Bloodlines.Castlevania.-.The.New.Generation.Vampire.Killer.zip)
It looks like this music doesn't use SSG-EG, but most converted music doesn't sound correctly.

**Comment by okaxaki** [comment]
Which version did you use? Some channels are ignored with the version <0.13.6.

**Comment by denjhang** [comment]
This issue has been resolved in 0.13.7
